server:
  port: 8130 # 服务端口

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos

  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5tQqMRnoRwDNC4GTMEd6
    keySecret: yBbBIZ3H86nhR7or22JQZUJ0nXDl9E
    bucketName: srb-client