server:
  port: 8130 # 服务端口

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos

  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
aliyun:
  oss:
    endpoint: 
    keyId: 
    keySecret: 
    bucketName: srb-client
